work_dir: ./output/uav-human/enhance/blockgcn_J_3d

# feeder
feeder: feeders.feeder_uav_human.FeederUAVHuman
train_feeder_args:
  data_path: ../data/uav-human/3d/train_joint_C.npy
  label_path: ../data/uav-human/3d/train_label_C.npy
  data_split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  data_path: ../data/uav-human/3d/val_joint_C.npy
  label_path: ../data/uav-human/3d/val_label_C.npy
  data_split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

# model
model: model.BlockGCN.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.Simcc.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.05
lr_decay_rate: 0.1
step: [110, 120]
warm_up_epoch: 5

# training
device: [0]
batch_size: 64
test_batch_size: 64
num_epoch: 140
nesterov: True
#start_epoch: 82
#weights: ./output/uav-human/blockgcn_J_3d/runs-81-17010.pt